added testing system in Makefile

diff --git a/tests/asm/Makefile.in b/tests/asm/Makefile.in
--- a/tests/asm/Makefile.in
+++ b/tests/asm/Makefile.in
@@ -11,8 +11,19 @@ ${TARGET}: ${SOLOUT} Makefile
 %.out: %.asm Makefile
 	${COMPILER} --assemble $< > $@
 
-run: ${TARGET}
+run: run-evm
+
+run-evm: ${TARGET}
 	../../../ethereum/build/bin/evm --gas $(GASLIMIT) --code `cat ${TARGET}.bin` run
 
+run-cemu: ${TARGET}
+	../../../emulator/bins/cemu -nt ../../../emulator/models/evm/simulator/evm.so ${TARGET}.bin
+
+compare: ${TARGET}
+	../../../ethereum/build/bin/evm --code `cat ${TARGET}.bin` run > out.evm
+	../../../emulator/bins/cemu -nt ../../../emulator/models/evm/simulator/evm.so ${TARGET}.bin > out.cemu
+	tail -n +2 out.cemu
+	bash -c 'diff -q out.evm out.cemu 1>/dev/null; if [ $$? -eq 0 ]; then echo "$? is PASSED"; else echo "$? is FAILD"; fi'
+
 clean:
-	rm -f ${TARGET}.bin ${SOLOUT}
+	rm -f ${TARGET}.bin ${SOLOUT} out.evm out.cemu
